[project]
name = "python-pocket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.3.0",
    "cryptography>=45.0.3",
    "customtkinter>=5.2.2",
    "tkcalendar>=1.6.1",
]
